apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwNTQuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImRHVnFZVHBVYUdGeWRXNTBaV3BoUURFeU13PT0iCgkJfQoJfQp9 
type: kubernetes.io/dockerconfigjson